name: CI

on:
  push:
    paths: ['**.rs', '**.toml', '**.lock', 'ci.yml']
  pull_request:
    paths: ['**.rs', '**.toml', '**.lock', 'ci.yml']

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: full check (${{ matrix.toolchain }} rust)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v4
      - name: switch to ${{ matrix.toolchain }} channel
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
          rustup component add rustfmt clippy
      - name: build
        run: cargo -b -v
      - name: fmt and clippy check
        run: cargo fmt -- --check ; cargo clippy -- -D warnings
      - name: test
        run: sudo ./.ci/test.sh
        
