name: CI

on:
  push:
    paths: ['**.rs', '**.toml', '**.lock', '**/ci.yml', '**/test.sh']
  pull_request:
    paths: ['**.rs', '**.toml', '**.lock', '**/ci.yml', '**/test.sh']

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: full check (${{ matrix.toolchain }} rust)
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v4
      - name: switch to ${{ matrix.toolchain }} channel
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
          rustup component add rustfmt clippy
      - name: build
        run: RUSTFLAGS="-C target-cpu=native" cargo b -v --locked
      - name: fmt and clippy check
        if: ${{ matrix.toolchain == 'nightly' }}
        run: |
          cargo fmt -- --check
          RUSTFLAGS="-C target-cpu=native" cargo clippy --locked -- -D warnings
      - name: test
        run: RUSTFLAGS="-C target-cpu=native" cargo t --locked --test '*'
